// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package grpc.common;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string eircode = 1;</code>
   */
  java.lang.String getEircode();
  /**
   * <code>string eircode = 1;</code>
   */
  com.google.protobuf.ByteString
      getEircodeBytes();

  /**
   * <code>string address = 2;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
