// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package grpc.common;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_FoodItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_FoodItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_FoodItemQuantity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_FoodItemQuantity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\006common\"$\n\010FoodItem\022\n\n\002id" +
      "\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"+\n\007Address\022\017\n\007eirco" +
      "de\030\001 \001(\t\022\017\n\007address\030\002 \001(\t\"D\n\020FoodItemQua" +
      "ntity\022\036\n\004item\030\001 \001(\0132\020.common.FoodItem\022\020\n" +
      "\010quantity\030\002 \001(\005B\017\n\013grpc.commonP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_FoodItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_FoodItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_FoodItem_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_common_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_Address_descriptor,
        new java.lang.String[] { "Eircode", "Address", });
    internal_static_common_FoodItemQuantity_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_common_FoodItemQuantity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_FoodItemQuantity_descriptor,
        new java.lang.String[] { "Item", "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
