// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package grpc.common;

public interface FoodItemQuantityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.FoodItemQuantity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The food item.
   * </pre>
   *
   * <code>.common.FoodItem item = 1;</code>
   */
  boolean hasItem();
  /**
   * <pre>
   * The food item.
   * </pre>
   *
   * <code>.common.FoodItem item = 1;</code>
   */
  grpc.common.FoodItem getItem();
  /**
   * <pre>
   * The food item.
   * </pre>
   *
   * <code>.common.FoodItem item = 1;</code>
   */
  grpc.common.FoodItemOrBuilder getItemOrBuilder();

  /**
   * <pre>
   * The quantity of that item.
   * </pre>
   *
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();
}
