// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package grpc.common;

public interface FoodItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.FoodItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
