// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logistics.proto

package grpc.logistics;

public interface DeliveryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logistics.Delivery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  java.util.List<grpc.common.FoodItemQuantity> 
      getItemsList();
  /**
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  grpc.common.FoodItemQuantity getItems(int index);
  /**
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  java.util.List<? extends grpc.common.FoodItemQuantityOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  grpc.common.FoodItemQuantityOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>.common.Address destination = 2;</code>
   */
  boolean hasDestination();
  /**
   * <code>.common.Address destination = 2;</code>
   */
  grpc.common.Address getDestination();
  /**
   * <code>.common.Address destination = 2;</code>
   */
  grpc.common.AddressOrBuilder getDestinationOrBuilder();

  /**
   * <code>.common.Address location = 3;</code>
   */
  boolean hasLocation();
  /**
   * <code>.common.Address location = 3;</code>
   */
  grpc.common.Address getLocation();
  /**
   * <code>.common.Address location = 3;</code>
   */
  grpc.common.AddressOrBuilder getLocationOrBuilder();
}
