// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logistics.proto

package grpc.logistics;

public interface DeliveryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logistics.DeliveryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool accepted = 1;</code>
   */
  boolean getAccepted();

  /**
   * <code>int32 delivery_id = 2;</code>
   */
  int getDeliveryId();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string pickup_time = 4;</code>
   */
  java.lang.String getPickupTime();
  /**
   * <code>string pickup_time = 4;</code>
   */
  com.google.protobuf.ByteString
      getPickupTimeBytes();
}
