// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logistics.proto

package grpc.logistics;

public interface LocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logistics.Location)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 delivery_id = 1;</code>
   */
  int getDeliveryId();

  /**
   * <code>string longitude = 2;</code>
   */
  java.lang.String getLongitude();
  /**
   * <code>string longitude = 2;</code>
   */
  com.google.protobuf.ByteString
      getLongitudeBytes();

  /**
   * <code>string latitude = 3;</code>
   */
  java.lang.String getLatitude();
  /**
   * <code>string latitude = 3;</code>
   */
  com.google.protobuf.ByteString
      getLatitudeBytes();

  /**
   * <code>string status = 4;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
