// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logistics.proto

package grpc.logistics;

public interface LocationUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logistics.LocationUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 delivery_id = 1;</code>
   */
  int getDeliveryId();
}
