// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logistics.proto

package grpc.logistics;

public final class Logistics {
  private Logistics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logistics_Delivery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_logistics_Delivery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logistics_DeliveryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_logistics_DeliveryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logistics_LocationUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_logistics_LocationUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_logistics_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_logistics_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017logistics.proto\022\tlogistics\032\014common.pro" +
      "to\"|\n\010Delivery\022\'\n\005items\030\001 \003(\0132\030.common.F" +
      "oodItemQuantity\022$\n\013destination\030\002 \001(\0132\017.c" +
      "ommon.Address\022!\n\010location\030\003 \001(\0132\017.common" +
      ".Address\"_\n\020DeliveryResponse\022\020\n\010accepted" +
      "\030\001 \001(\010\022\023\n\013delivery_id\030\002 \001(\005\022\017\n\007message\030\003" +
      " \001(\t\022\023\n\013pickup_time\030\004 \001(\t\"%\n\016LocationUpd" +
      "ate\022\023\n\013delivery_id\030\001 \001(\005\"T\n\010Location\022\023\n\013" +
      "delivery_id\030\001 \001(\005\022\021\n\tlongitude\030\002 \001(\t\022\020\n\010" +
      "latitude\030\003 \001(\t\022\016\n\006status\030\004 \001(\t2\242\001\n\020Logis" +
      "ticsService\022I\n\025handleDeliveryRequest\022\023.l" +
      "ogistics.Delivery\032\033.logistics.DeliveryRe" +
      "sponse\022C\n\rtrackDelivery\022\031.logistics.Loca" +
      "tionUpdate\032\023.logistics.Location(\0010\001B\022\n\016g" +
      "rpc.logisticsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc.common.Common.getDescriptor(),
        }, assigner);
    internal_static_logistics_Delivery_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_logistics_Delivery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_logistics_Delivery_descriptor,
        new java.lang.String[] { "Items", "Destination", "Location", });
    internal_static_logistics_DeliveryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_logistics_DeliveryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_logistics_DeliveryResponse_descriptor,
        new java.lang.String[] { "Accepted", "DeliveryId", "Message", "PickupTime", });
    internal_static_logistics_LocationUpdate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_logistics_LocationUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_logistics_LocationUpdate_descriptor,
        new java.lang.String[] { "DeliveryId", });
    internal_static_logistics_Location_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_logistics_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_logistics_Location_descriptor,
        new java.lang.String[] { "DeliveryId", "Longitude", "Latitude", "Status", });
    grpc.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
