// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_hub.proto

package grpc.smart_hub;

public interface FoodRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_hub.FoodRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * array of food items
   * </pre>
   *
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  java.util.List<grpc.common.FoodItemQuantity> 
      getItemsList();
  /**
   * <pre>
   * array of food items
   * </pre>
   *
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  grpc.common.FoodItemQuantity getItems(int index);
  /**
   * <pre>
   * array of food items
   * </pre>
   *
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  int getItemsCount();
  /**
   * <pre>
   * array of food items
   * </pre>
   *
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  java.util.List<? extends grpc.common.FoodItemQuantityOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <pre>
   * array of food items
   * </pre>
   *
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  grpc.common.FoodItemQuantityOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>.common.Address destination = 2;</code>
   */
  boolean hasDestination();
  /**
   * <code>.common.Address destination = 2;</code>
   */
  grpc.common.Address getDestination();
  /**
   * <code>.common.Address destination = 2;</code>
   */
  grpc.common.AddressOrBuilder getDestinationOrBuilder();

  /**
   * <code>int32 request_id = 3;</code>
   */
  int getRequestId();
}
