// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_hub.proto

package grpc.smart_hub;

/**
 * Protobuf type {@code smart_hub.FoodRequest}
 */
public  final class FoodRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smart_hub.FoodRequest)
    FoodRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FoodRequest.newBuilder() to construct.
  private FoodRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FoodRequest() {
    items_ = java.util.Collections.emptyList();
    requestId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FoodRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              items_ = new java.util.ArrayList<grpc.common.FoodItemQuantity>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(
                input.readMessage(grpc.common.FoodItemQuantity.parser(), extensionRegistry));
            break;
          }
          case 18: {
            grpc.common.Address.Builder subBuilder = null;
            if (destination_ != null) {
              subBuilder = destination_.toBuilder();
            }
            destination_ = input.readMessage(grpc.common.Address.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(destination_);
              destination_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            requestId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.smart_hub.SmartHub.internal_static_smart_hub_FoodRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.smart_hub.SmartHub.internal_static_smart_hub_FoodRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.smart_hub.FoodRequest.class, grpc.smart_hub.FoodRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ITEMS_FIELD_NUMBER = 1;
  private java.util.List<grpc.common.FoodItemQuantity> items_;
  /**
   * <pre>
   * array of food items
   * </pre>
   *
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  public java.util.List<grpc.common.FoodItemQuantity> getItemsList() {
    return items_;
  }
  /**
   * <pre>
   * array of food items
   * </pre>
   *
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  public java.util.List<? extends grpc.common.FoodItemQuantityOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <pre>
   * array of food items
   * </pre>
   *
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <pre>
   * array of food items
   * </pre>
   *
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  public grpc.common.FoodItemQuantity getItems(int index) {
    return items_.get(index);
  }
  /**
   * <pre>
   * array of food items
   * </pre>
   *
   * <code>repeated .common.FoodItemQuantity items = 1;</code>
   */
  public grpc.common.FoodItemQuantityOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int DESTINATION_FIELD_NUMBER = 2;
  private grpc.common.Address destination_;
  /**
   * <code>.common.Address destination = 2;</code>
   */
  public boolean hasDestination() {
    return destination_ != null;
  }
  /**
   * <code>.common.Address destination = 2;</code>
   */
  public grpc.common.Address getDestination() {
    return destination_ == null ? grpc.common.Address.getDefaultInstance() : destination_;
  }
  /**
   * <code>.common.Address destination = 2;</code>
   */
  public grpc.common.AddressOrBuilder getDestinationOrBuilder() {
    return getDestination();
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 3;
  private int requestId_;
  /**
   * <code>int32 request_id = 3;</code>
   */
  public int getRequestId() {
    return requestId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    if (destination_ != null) {
      output.writeMessage(2, getDestination());
    }
    if (requestId_ != 0) {
      output.writeInt32(3, requestId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    if (destination_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDestination());
    }
    if (requestId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, requestId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.smart_hub.FoodRequest)) {
      return super.equals(obj);
    }
    grpc.smart_hub.FoodRequest other = (grpc.smart_hub.FoodRequest) obj;

    boolean result = true;
    result = result && getItemsList()
        .equals(other.getItemsList());
    result = result && (hasDestination() == other.hasDestination());
    if (hasDestination()) {
      result = result && getDestination()
          .equals(other.getDestination());
    }
    result = result && (getRequestId()
        == other.getRequestId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    if (hasDestination()) {
      hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + getDestination().hashCode();
    }
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.smart_hub.FoodRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smart_hub.FoodRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smart_hub.FoodRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smart_hub.FoodRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smart_hub.FoodRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smart_hub.FoodRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smart_hub.FoodRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.smart_hub.FoodRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.smart_hub.FoodRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.smart_hub.FoodRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.smart_hub.FoodRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.smart_hub.FoodRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.smart_hub.FoodRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smart_hub.FoodRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smart_hub.FoodRequest)
      grpc.smart_hub.FoodRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.smart_hub.SmartHub.internal_static_smart_hub_FoodRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.smart_hub.SmartHub.internal_static_smart_hub_FoodRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.smart_hub.FoodRequest.class, grpc.smart_hub.FoodRequest.Builder.class);
    }

    // Construct using grpc.smart_hub.FoodRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      if (destinationBuilder_ == null) {
        destination_ = null;
      } else {
        destination_ = null;
        destinationBuilder_ = null;
      }
      requestId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.smart_hub.SmartHub.internal_static_smart_hub_FoodRequest_descriptor;
    }

    @java.lang.Override
    public grpc.smart_hub.FoodRequest getDefaultInstanceForType() {
      return grpc.smart_hub.FoodRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.smart_hub.FoodRequest build() {
      grpc.smart_hub.FoodRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.smart_hub.FoodRequest buildPartial() {
      grpc.smart_hub.FoodRequest result = new grpc.smart_hub.FoodRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      if (destinationBuilder_ == null) {
        result.destination_ = destination_;
      } else {
        result.destination_ = destinationBuilder_.build();
      }
      result.requestId_ = requestId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.smart_hub.FoodRequest) {
        return mergeFrom((grpc.smart_hub.FoodRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.smart_hub.FoodRequest other) {
      if (other == grpc.smart_hub.FoodRequest.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (other.hasDestination()) {
        mergeDestination(other.getDestination());
      }
      if (other.getRequestId() != 0) {
        setRequestId(other.getRequestId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.smart_hub.FoodRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.smart_hub.FoodRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.common.FoodItemQuantity> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        items_ = new java.util.ArrayList<grpc.common.FoodItemQuantity>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.common.FoodItemQuantity, grpc.common.FoodItemQuantity.Builder, grpc.common.FoodItemQuantityOrBuilder> itemsBuilder_;

    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public java.util.List<grpc.common.FoodItemQuantity> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public grpc.common.FoodItemQuantity getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public Builder setItems(
        int index, grpc.common.FoodItemQuantity value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public Builder setItems(
        int index, grpc.common.FoodItemQuantity.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public Builder addItems(grpc.common.FoodItemQuantity value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public Builder addItems(
        int index, grpc.common.FoodItemQuantity value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public Builder addItems(
        grpc.common.FoodItemQuantity.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public Builder addItems(
        int index, grpc.common.FoodItemQuantity.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends grpc.common.FoodItemQuantity> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public grpc.common.FoodItemQuantity.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public grpc.common.FoodItemQuantityOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public java.util.List<? extends grpc.common.FoodItemQuantityOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public grpc.common.FoodItemQuantity.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          grpc.common.FoodItemQuantity.getDefaultInstance());
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public grpc.common.FoodItemQuantity.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, grpc.common.FoodItemQuantity.getDefaultInstance());
    }
    /**
     * <pre>
     * array of food items
     * </pre>
     *
     * <code>repeated .common.FoodItemQuantity items = 1;</code>
     */
    public java.util.List<grpc.common.FoodItemQuantity.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.common.FoodItemQuantity, grpc.common.FoodItemQuantity.Builder, grpc.common.FoodItemQuantityOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.common.FoodItemQuantity, grpc.common.FoodItemQuantity.Builder, grpc.common.FoodItemQuantityOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private grpc.common.Address destination_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.common.Address, grpc.common.Address.Builder, grpc.common.AddressOrBuilder> destinationBuilder_;
    /**
     * <code>.common.Address destination = 2;</code>
     */
    public boolean hasDestination() {
      return destinationBuilder_ != null || destination_ != null;
    }
    /**
     * <code>.common.Address destination = 2;</code>
     */
    public grpc.common.Address getDestination() {
      if (destinationBuilder_ == null) {
        return destination_ == null ? grpc.common.Address.getDefaultInstance() : destination_;
      } else {
        return destinationBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.Address destination = 2;</code>
     */
    public Builder setDestination(grpc.common.Address value) {
      if (destinationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        destination_ = value;
        onChanged();
      } else {
        destinationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.common.Address destination = 2;</code>
     */
    public Builder setDestination(
        grpc.common.Address.Builder builderForValue) {
      if (destinationBuilder_ == null) {
        destination_ = builderForValue.build();
        onChanged();
      } else {
        destinationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.common.Address destination = 2;</code>
     */
    public Builder mergeDestination(grpc.common.Address value) {
      if (destinationBuilder_ == null) {
        if (destination_ != null) {
          destination_ =
            grpc.common.Address.newBuilder(destination_).mergeFrom(value).buildPartial();
        } else {
          destination_ = value;
        }
        onChanged();
      } else {
        destinationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.common.Address destination = 2;</code>
     */
    public Builder clearDestination() {
      if (destinationBuilder_ == null) {
        destination_ = null;
        onChanged();
      } else {
        destination_ = null;
        destinationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.common.Address destination = 2;</code>
     */
    public grpc.common.Address.Builder getDestinationBuilder() {
      
      onChanged();
      return getDestinationFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.Address destination = 2;</code>
     */
    public grpc.common.AddressOrBuilder getDestinationOrBuilder() {
      if (destinationBuilder_ != null) {
        return destinationBuilder_.getMessageOrBuilder();
      } else {
        return destination_ == null ?
            grpc.common.Address.getDefaultInstance() : destination_;
      }
    }
    /**
     * <code>.common.Address destination = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.common.Address, grpc.common.Address.Builder, grpc.common.AddressOrBuilder> 
        getDestinationFieldBuilder() {
      if (destinationBuilder_ == null) {
        destinationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.common.Address, grpc.common.Address.Builder, grpc.common.AddressOrBuilder>(
                getDestination(),
                getParentForChildren(),
                isClean());
        destination_ = null;
      }
      return destinationBuilder_;
    }

    private int requestId_ ;
    /**
     * <code>int32 request_id = 3;</code>
     */
    public int getRequestId() {
      return requestId_;
    }
    /**
     * <code>int32 request_id = 3;</code>
     */
    public Builder setRequestId(int value) {
      
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 request_id = 3;</code>
     */
    public Builder clearRequestId() {
      
      requestId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smart_hub.FoodRequest)
  }

  // @@protoc_insertion_point(class_scope:smart_hub.FoodRequest)
  private static final grpc.smart_hub.FoodRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.smart_hub.FoodRequest();
  }

  public static grpc.smart_hub.FoodRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FoodRequest>
      PARSER = new com.google.protobuf.AbstractParser<FoodRequest>() {
    @java.lang.Override
    public FoodRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FoodRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FoodRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FoodRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.smart_hub.FoodRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

