// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_hub.proto

package grpc.smart_hub;

public interface SavedFoodRequestsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_hub.SavedFoodRequests)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .common.SavedFoodRequest items = 1;</code>
   */
  java.util.List<grpc.common.SavedFoodRequest> 
      getItemsList();
  /**
   * <code>repeated .common.SavedFoodRequest items = 1;</code>
   */
  grpc.common.SavedFoodRequest getItems(int index);
  /**
   * <code>repeated .common.SavedFoodRequest items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .common.SavedFoodRequest items = 1;</code>
   */
  java.util.List<? extends grpc.common.SavedFoodRequestOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .common.SavedFoodRequest items = 1;</code>
   */
  grpc.common.SavedFoodRequestOrBuilder getItemsOrBuilder(
      int index);
}
