// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_hub.proto

package grpc.smart_hub;

public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_hub.StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 delivery_id = 2;</code>
   */
  int getDeliveryId();

  /**
   * <code>string pickup_time = 3;</code>
   */
  java.lang.String getPickupTime();
  /**
   * <code>string pickup_time = 3;</code>
   */
  com.google.protobuf.ByteString
      getPickupTimeBytes();
}
