// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_hub.proto

package grpc.smart_hub;

public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smart_hub.StatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 request_id = 1;</code>
   */
  int getRequestId();
}
