// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: food_source.proto

package grpc.food_source;

public final class FoodSource {
  private FoodSource() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021food_source.proto\022\013food_source\032\014common" +
      ".proto2T\n\021FoodSourceService\022?\n\030StreamAva" +
      "ilableFoodItems\022\017.common.Address\032\020.commo" +
      "n.FoodItem0\001B\024\n\020grpc.food_sourceP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc.common.Common.getDescriptor(),
        }, assigner);
    grpc.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
