// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: food_source.proto

package grpc.food_source;

public final class FoodSource {
  private FoodSource() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_food_source_Stock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_food_source_Stock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_food_source_StockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_food_source_StockResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021food_source.proto\022\013food_source\032\014common" +
      ".proto\"N\n\005Stock\022 \n\007address\030\001 \001(\0132\017.commo" +
      "n.Address\022\017\n\007instock\030\002 \001(\010\022\022\n\nrequest_id" +
      "\030\003 \001(\005\"2\n\rStockResponse\022!\n\005stock\030\001 \003(\0132\022" +
      ".food_source.Stock2\263\001\n\021FoodSourceService" +
      "\022G\n\030streamAvailableFoodItems\022\017.common.Ad" +
      "dress\032\030.common.FoodItemQuantity0\001\022U\n\033che" +
      "ckIfFoodRequestIsInStock\022\030.common.SavedF" +
      "oodRequest\032\032.food_source.StockResponse(\001" +
      "B\024\n\020grpc.food_sourceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc.common.Common.getDescriptor(),
        }, assigner);
    internal_static_food_source_Stock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_food_source_Stock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_food_source_Stock_descriptor,
        new java.lang.String[] { "Address", "Instock", "RequestId", });
    internal_static_food_source_StockResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_food_source_StockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_food_source_StockResponse_descriptor,
        new java.lang.String[] { "Stock", });
    grpc.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
