// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: food_source.proto

package grpc.food_source;

public interface StockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:food_source.StockResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .food_source.Stock stock = 1;</code>
   */
  java.util.List<grpc.food_source.Stock> 
      getStockList();
  /**
   * <code>repeated .food_source.Stock stock = 1;</code>
   */
  grpc.food_source.Stock getStock(int index);
  /**
   * <code>repeated .food_source.Stock stock = 1;</code>
   */
  int getStockCount();
  /**
   * <code>repeated .food_source.Stock stock = 1;</code>
   */
  java.util.List<? extends grpc.food_source.StockOrBuilder> 
      getStockOrBuilderList();
  /**
   * <code>repeated .food_source.Stock stock = 1;</code>
   */
  grpc.food_source.StockOrBuilder getStockOrBuilder(
      int index);
}
