// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: food_source.proto

package grpc.food_source;

/**
 * Protobuf type {@code food_source.StockResponse}
 */
public  final class StockResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:food_source.StockResponse)
    StockResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StockResponse.newBuilder() to construct.
  private StockResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StockResponse() {
    stock_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StockResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              stock_ = new java.util.ArrayList<grpc.food_source.Stock>();
              mutable_bitField0_ |= 0x00000001;
            }
            stock_.add(
                input.readMessage(grpc.food_source.Stock.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        stock_ = java.util.Collections.unmodifiableList(stock_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.food_source.FoodSource.internal_static_food_source_StockResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.food_source.FoodSource.internal_static_food_source_StockResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.food_source.StockResponse.class, grpc.food_source.StockResponse.Builder.class);
  }

  public static final int STOCK_FIELD_NUMBER = 1;
  private java.util.List<grpc.food_source.Stock> stock_;
  /**
   * <code>repeated .food_source.Stock stock = 1;</code>
   */
  public java.util.List<grpc.food_source.Stock> getStockList() {
    return stock_;
  }
  /**
   * <code>repeated .food_source.Stock stock = 1;</code>
   */
  public java.util.List<? extends grpc.food_source.StockOrBuilder> 
      getStockOrBuilderList() {
    return stock_;
  }
  /**
   * <code>repeated .food_source.Stock stock = 1;</code>
   */
  public int getStockCount() {
    return stock_.size();
  }
  /**
   * <code>repeated .food_source.Stock stock = 1;</code>
   */
  public grpc.food_source.Stock getStock(int index) {
    return stock_.get(index);
  }
  /**
   * <code>repeated .food_source.Stock stock = 1;</code>
   */
  public grpc.food_source.StockOrBuilder getStockOrBuilder(
      int index) {
    return stock_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < stock_.size(); i++) {
      output.writeMessage(1, stock_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < stock_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, stock_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.food_source.StockResponse)) {
      return super.equals(obj);
    }
    grpc.food_source.StockResponse other = (grpc.food_source.StockResponse) obj;

    boolean result = true;
    result = result && getStockList()
        .equals(other.getStockList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStockCount() > 0) {
      hash = (37 * hash) + STOCK_FIELD_NUMBER;
      hash = (53 * hash) + getStockList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.food_source.StockResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.food_source.StockResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.food_source.StockResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.food_source.StockResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.food_source.StockResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.food_source.StockResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.food_source.StockResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.food_source.StockResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.food_source.StockResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.food_source.StockResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.food_source.StockResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.food_source.StockResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.food_source.StockResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code food_source.StockResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:food_source.StockResponse)
      grpc.food_source.StockResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.food_source.FoodSource.internal_static_food_source_StockResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.food_source.FoodSource.internal_static_food_source_StockResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.food_source.StockResponse.class, grpc.food_source.StockResponse.Builder.class);
    }

    // Construct using grpc.food_source.StockResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStockFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (stockBuilder_ == null) {
        stock_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        stockBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.food_source.FoodSource.internal_static_food_source_StockResponse_descriptor;
    }

    @java.lang.Override
    public grpc.food_source.StockResponse getDefaultInstanceForType() {
      return grpc.food_source.StockResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.food_source.StockResponse build() {
      grpc.food_source.StockResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.food_source.StockResponse buildPartial() {
      grpc.food_source.StockResponse result = new grpc.food_source.StockResponse(this);
      int from_bitField0_ = bitField0_;
      if (stockBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          stock_ = java.util.Collections.unmodifiableList(stock_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.stock_ = stock_;
      } else {
        result.stock_ = stockBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.food_source.StockResponse) {
        return mergeFrom((grpc.food_source.StockResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.food_source.StockResponse other) {
      if (other == grpc.food_source.StockResponse.getDefaultInstance()) return this;
      if (stockBuilder_ == null) {
        if (!other.stock_.isEmpty()) {
          if (stock_.isEmpty()) {
            stock_ = other.stock_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStockIsMutable();
            stock_.addAll(other.stock_);
          }
          onChanged();
        }
      } else {
        if (!other.stock_.isEmpty()) {
          if (stockBuilder_.isEmpty()) {
            stockBuilder_.dispose();
            stockBuilder_ = null;
            stock_ = other.stock_;
            bitField0_ = (bitField0_ & ~0x00000001);
            stockBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStockFieldBuilder() : null;
          } else {
            stockBuilder_.addAllMessages(other.stock_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.food_source.StockResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.food_source.StockResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.food_source.Stock> stock_ =
      java.util.Collections.emptyList();
    private void ensureStockIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        stock_ = new java.util.ArrayList<grpc.food_source.Stock>(stock_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.food_source.Stock, grpc.food_source.Stock.Builder, grpc.food_source.StockOrBuilder> stockBuilder_;

    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public java.util.List<grpc.food_source.Stock> getStockList() {
      if (stockBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stock_);
      } else {
        return stockBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public int getStockCount() {
      if (stockBuilder_ == null) {
        return stock_.size();
      } else {
        return stockBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public grpc.food_source.Stock getStock(int index) {
      if (stockBuilder_ == null) {
        return stock_.get(index);
      } else {
        return stockBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public Builder setStock(
        int index, grpc.food_source.Stock value) {
      if (stockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockIsMutable();
        stock_.set(index, value);
        onChanged();
      } else {
        stockBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public Builder setStock(
        int index, grpc.food_source.Stock.Builder builderForValue) {
      if (stockBuilder_ == null) {
        ensureStockIsMutable();
        stock_.set(index, builderForValue.build());
        onChanged();
      } else {
        stockBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public Builder addStock(grpc.food_source.Stock value) {
      if (stockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockIsMutable();
        stock_.add(value);
        onChanged();
      } else {
        stockBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public Builder addStock(
        int index, grpc.food_source.Stock value) {
      if (stockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockIsMutable();
        stock_.add(index, value);
        onChanged();
      } else {
        stockBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public Builder addStock(
        grpc.food_source.Stock.Builder builderForValue) {
      if (stockBuilder_ == null) {
        ensureStockIsMutable();
        stock_.add(builderForValue.build());
        onChanged();
      } else {
        stockBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public Builder addStock(
        int index, grpc.food_source.Stock.Builder builderForValue) {
      if (stockBuilder_ == null) {
        ensureStockIsMutable();
        stock_.add(index, builderForValue.build());
        onChanged();
      } else {
        stockBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public Builder addAllStock(
        java.lang.Iterable<? extends grpc.food_source.Stock> values) {
      if (stockBuilder_ == null) {
        ensureStockIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stock_);
        onChanged();
      } else {
        stockBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public Builder clearStock() {
      if (stockBuilder_ == null) {
        stock_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        stockBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public Builder removeStock(int index) {
      if (stockBuilder_ == null) {
        ensureStockIsMutable();
        stock_.remove(index);
        onChanged();
      } else {
        stockBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public grpc.food_source.Stock.Builder getStockBuilder(
        int index) {
      return getStockFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public grpc.food_source.StockOrBuilder getStockOrBuilder(
        int index) {
      if (stockBuilder_ == null) {
        return stock_.get(index);  } else {
        return stockBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public java.util.List<? extends grpc.food_source.StockOrBuilder> 
         getStockOrBuilderList() {
      if (stockBuilder_ != null) {
        return stockBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stock_);
      }
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public grpc.food_source.Stock.Builder addStockBuilder() {
      return getStockFieldBuilder().addBuilder(
          grpc.food_source.Stock.getDefaultInstance());
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public grpc.food_source.Stock.Builder addStockBuilder(
        int index) {
      return getStockFieldBuilder().addBuilder(
          index, grpc.food_source.Stock.getDefaultInstance());
    }
    /**
     * <code>repeated .food_source.Stock stock = 1;</code>
     */
    public java.util.List<grpc.food_source.Stock.Builder> 
         getStockBuilderList() {
      return getStockFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.food_source.Stock, grpc.food_source.Stock.Builder, grpc.food_source.StockOrBuilder> 
        getStockFieldBuilder() {
      if (stockBuilder_ == null) {
        stockBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.food_source.Stock, grpc.food_source.Stock.Builder, grpc.food_source.StockOrBuilder>(
                stock_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        stock_ = null;
      }
      return stockBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:food_source.StockResponse)
  }

  // @@protoc_insertion_point(class_scope:food_source.StockResponse)
  private static final grpc.food_source.StockResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.food_source.StockResponse();
  }

  public static grpc.food_source.StockResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StockResponse>
      PARSER = new com.google.protobuf.AbstractParser<StockResponse>() {
    @java.lang.Override
    public StockResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StockResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StockResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StockResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.food_source.StockResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

