// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: food_source.proto

package grpc.food_source;

public interface StockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:food_source.Stock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.Address address = 1;</code>
   */
  boolean hasAddress();
  /**
   * <code>.common.Address address = 1;</code>
   */
  grpc.common.Address getAddress();
  /**
   * <code>.common.Address address = 1;</code>
   */
  grpc.common.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>bool instock = 2;</code>
   */
  boolean getInstock();

  /**
   * <code>int32 request_id = 3;</code>
   */
  int getRequestId();
}
